"""Add Enterprise Transaction Model

Revision ID: 576701fe05eb
Revises: f9cf819fcac3
Create Date: 2026-07-24 09:54:38.924353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576701fe05eb'
down_revision: Union[str, Sequence[str], None] = 'f9cf819fcac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_date', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('transaction_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('subcategory', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('merchant', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('receipt_image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_transactions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_merchant'), ['merchant'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('type')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_merchant'))
        batch_op.drop_index(batch_op.f('ix_transactions_category'))
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('receipt_image')
        batch_op.drop_column('tags')
        batch_op.drop_column('notes')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('merchant')
        batch_op.drop_column('currency')
        batch_op.drop_column('subcategory')
        batch_op.drop_column('transaction_type')
        batch_op.drop_column('transaction_date')

    # ### end Alembic commands ###
