"""Add import schemas

Revision ID: e56ac201dc70
Revises: 576701fe05eb
Create Date: 2026-07-28 09:21:08.618097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56ac201dc70'
down_revision: Union[str, Sequence[str], None] = '576701fe05eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('duplicates_found', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('import_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('raw_data', sa.String(), nullable=False),
    sa.Column('parsed_amount', sa.Float(), nullable=True),
    sa.Column('parsed_date', sa.String(), nullable=True),
    sa.Column('parsed_merchant', sa.String(), nullable=True),
    sa.Column('ai_category_suggestion', sa.String(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['import_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_records_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_records_session_id'))
        batch_op.drop_index(batch_op.f('ix_import_records_id'))

    op.drop_table('import_records')
    with op.batch_alter_table('import_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_import_sessions_id'))

    op.drop_table('import_sessions')
    # ### end Alembic commands ###
